create table PhanLoai (
	NhomPhanLoai Nvarchar(255) not null,
	ID int primary key  identity,
	TenPhanLoai Nvarchar(255) not null,
);

create table LoaiSanPham (
	ID int primary key identity,
	TenLoai Nvarchar(255) not null,
	PhanLoaiID int foreign key references PhanLoai(ID),
);

create table ThuongHieu (
	ID int primary key identity,
	TenThuongHieu Nvarchar(255)
);

create table SanPham (
	LoaiSanPhamID int foreign key references LoaiSanPham(ID),
	ID int primary key identity,
	TenSanPham Nvarchar(255) not null,
	Gia decimal(12,4) check (Gia > 0) not null,
	SoLuong int check (SoLuong >=0),
	ThuongHieuID int foreign key references ThuongHieu(ID),
	TrangThai Nvarchar(255),
);


create table AnhSanPham (
	ID int primary key identity,
	Image varchar(255) not null,
	SanPhamID int foreign key references SanPham(ID),
);


create table ThongSo (
	ID int primary key identity,
	SanPhamID int foreign key references SanPham(ID),
	ThuocTinh Nvarchar(255) not null,
	GiaTri Nvarchar(255) not null,
);


create table BinhLuan (
	ID int primary key identity,
	SanPhamID int foreign key references SanPham(ID),
	Ten Nvarchar (255) not null,
	SoDienThoai int,
	NoiDung Ntext not null,
);

create table MoTaSp (
	ID int primary key identity,
	SanPhamID int foreign key references SanPham(ID),
	image varchar(255),
	TieuDe text not null,
);

create table SubBinhLuan (
	ID int primary key identity,
	BinhLuanID int foreign key references BinhLuan(ID),
	Ten Nvarchar(255) not null,
	SoDienThoai int,
	NoiDung text not null,
);

create table SubMoTa (
	ID int primary key identity,
	MoTaSpID int foreign key references MoTaSp(ID),
	TieuDe text,
	NoiDung text,
	Image varchar(255),
	NoiDungThem text,
	ImageThem varchar(255),
);




insert into PhanLoai (NhomPhanLoai,TenPhanLoai)
	values (N'Tivi, Loa, Âm Thanh','Tivi'),
		(N'Tivi, Loa, Âm Thanh',N'Loa Âm Thanh'),
		(N'Tủ Lạnh, Tủ đông, Tủ Mát', N'Tủ Lạnh'),
		(N'Tủ Lạnh, Tủ đông, Tủ Mát',N'Tủ Đông'),
		(N'Tủ Lạnh, Tủ đông, Tủ Mát',N'Tủ Mát'),
		(N'Tủ Lạnh, Tủ đông, Tủ Mát',N'Tủ Ướp Lạnh Rượu'),
		(N'Mát giặt, sấy quần áo',N'Máy Giặt'),
		(N'Mát giặt, sấy quần áo',N'Máy Sấy'),
		(N'Điều hoà nhiệt độ', N'Loại Điều Hoà'),
		(N'Điều hoà nhiệt độ', N'Tiêu Chí Lựa Chọn'),
		(N'Bình nóng lạnh, lọc nước', N'Máy Lọc Nước'),
		(N'Bình nóng lạnh, lọc nước', N'Cây Nước Nóng Lạnh'),
		(N'Điện gia dụng', N'Dụng Cụ Nhà Bếp'),
		(N'Điện gia dụng', N'Thiết Bị Gia Đình'),
		(N'Điện gia dụng', N'Sản Phẩm Khác'),
		(N'Laptop, Điện Thoại',	N'Laptop'),
		(N'Laptop, Điện Thoại',N'Điện thoại'),
		(N'Laptop, Điện Thoại',N'Tablet'),
		(N'PC, Màn hình, Máy văn phòng',N'Máy tính để bàn'),
		(N'PC, Màn hình, Máy văn phòng',N'Màn hình máy tính'),
		(N'PC, Màn hình, Máy văn phòng',N'Máy văn phòng'),
		(N'Đồng hồ, Máy ảnh',N'Đồng hồ'),
		(N'Đồng hồ, Máy ảnh',N'Kỹ thuật số'),
		(N'Đồng hồ, Máy ảnh',N'Phụ kiện');

insert into ThuongHieu (TenThuongHieu)
	values('Sam Sung'),
		('LG'),
		('Sony'),
		('TLC'),
		('Panasonic'),
		('Sharp'),
		('Toshiba'),
		('Hitachi'),
		('Aqua'),
		('Electrolux'),
		('Mitsubishi'),
		('Beko'),
		('Daikin'),
		('Casper'),
		('KDK'),
		('Kangaroo'),
		('Sanaky'),
		('Alaska'),
		('Gree'),
		('Ariston'),
		('Ferroli'),
		('Karofi'),
		('A.O Smith'),
		('Hyundai'),
		('Sunhouse'),
		('Fujie'),
		('Coway');

insert into LoaiSanPham (PhanLoaiID, TenLoai) 
	values(1, N'Tivi 8k'),
		(1, N'Tivi 4k'),
		(1, N'OLED'),
		(1, N'Neo QLED'),
		(1, N'Smart Tivi'),
		(1, N'Lifestyle Tivi'),
		(1, N'Tivi LED Thường'),
		(2, N'Loa thanh Soundbar'),
		(2, N'Dàn âm thanh'),
		(2, N'Lao kéo'), 
		(2, N'Android TV Box'),
		(3, N'Tủ Lạng Mini'),
		(3, N'Tủ Lạnh 2 Cánh'),
		(3, N'Tủ lạnh 3,4 cánh'),
		(3, N'Tủ lạnh 5 cánh'),
		(3, N'Tủ lạnh Side by side'),
		(4, N'Sanaky'),
		(4, N'Kangaroo'),
		(4, N'Alaska'),
		(5, N'Sanaky'),
		(5, N'Kangaroo'),
		(5, N'Alaska'),
		(6, 'Electrolux'),
		(6, 'KDK'),
		(7,	N'Macbook'),
		(7,	N'Dell'),
		(7,	N'Asus'),
		(7, N'Hp'),
		(7, N'Acer'),
		(7, N'Lenovo'),
		(7, N'LG'),
		(7, N'Gigabyte'),
		(8, N'Sam Sung'),
		(8, N'IPhone'),
		(8, N'Oppo'),
		(8, N'Nokia'),
		(8, N'Vivo'),
		(8, N'Realme'),
		(8, N'Masstel'),
		(8, N'Xiaomi'),
		(8, N'Vsmart'),
		(8, N'Huawei'),
		(9, N'Ipad'),
		(9, N'Samsung'),
		(10, N'Dell'),
		(10, N'Hp'),
		(10, N'Apple'),
		(10, N'SingPc'),
		(10, N'Lenovo'),
		(10, N'Asus'),
		(11, N'Dell'),
		(11, N'HP'),
		(11, N'SamSung'),
		(11, N'Acer'),
		(11, N'Lenovo'),
		(11, N'Asus'),
		(11, N'LG'),
		(12, N'Máy in'),
		(12, N'Máy chiếu'),
		(12, N'Máy scan'),
		(12, N'Máy đếm tiền'),
		(12, N'Máy tính tay'),
		(12, N'Máy huỷ tài liệu'),
		(12, N'Bộ phụ kiện máy chiếu'),
		(12, N'Điện thoại bàn'),
		(13, N'Apple'),
		(13, N'Samsung'),
		(13, N'Masstel'),
		(14, N'Máy ảnh'),
		(14, N'Máy quay'),
		(15, N'Loa vi tính'),
		(15, N'Thiết bị lưu trữ'),
		(15, N'Thiết bị mạng'),
		(15, N'Chuột & bàn phím'),
		(15, N'Tai nghe'),
		(15, N'Loa bluetooth'),
		(15, N'Pin sạc dự phòng'),
		(15, N'Cáp, củ sạc, đầu đọc thẻ');

		select * from ThuongHieu
		

insert into SanPham(LoaiSanPhamID,ID, TenSanPham,Gia,SoLuong,ThuongHieuID)
	values(1,1, N'Smart Tivi LG NanoCell 8K 55 inch 55NANO95TNA',28990000,10,2),
		(1,2,N'Smart Tivi LG NanoCell 8K 75 inch 75NANO95TPA',109890000,10,2),
		(1,3,N'Smart Tivi QLED Samsung 8K 75 inch QA75Q950TS',139890000,10,2),
		(1,4,N'Smart Tivi QLED Samsung 8K 75 inch QA75Q900R',71990000,10,1),
		(1,5,N'Smart Tivi QLED Samsung 8K 82 inch QA82Q900R',104990000,10,1),
		(1,6,N'Smart Tivi QLED Samsung 8K 75 inch QA75Q800T',79990000,10,1),
		(1,7,N'Smart Tivi LG NanoCell 8K 75 inch 75NANO95TNA',52590000,10,2,



insert into AnhSanPham(SanPhamID,Image)
	values(1,'https://hc.com.vn/i/ecommerce/media/AV.001708_FEATURE_67662.jpg'),
		(1,'https://hc.com.vn/i/ecommerce/media/AV.001708_FEATURE_67664.jpg'),
		(1,'https://hc.com.vn/i/ecommerce/media/AV.001708_FEATURE_67671.jpg'),
		(1,'https://hc.com.vn/i/ecommerce/media/AV.001708_FEATURE_67672.jpg'),
		(1,'https://hc.com.vn/i/ecommerce/media/AV.001708_FEATURE_67674.jpg'),
		(2,'https://hc.com.vn/i/ecommerce/media/AV.002410_FEATURE_85641.jpg'),
		(2,'https://hc.com.vn/i/ecommerce/media/AV.002410_FEATURE_85642.jpg'),
		(2,'https://hc.com.vn/i/ecommerce/media/AV.002410_FEATURE_85643.jpg'),
		(2,'https://hc.com.vn/i/ecommerce/media/AV.002410_FEATURE_85644.jpg'),
		(2,'https://hc.com.vn/i/ecommerce/media/AV.002410_FEATURE_85645.jpg'),
		(2,'https://hc.com.vn/i/ecommerce/media/AV.002410_FEATURE_85646.jpg'),
		(3,'https://hc.com.vn/i/ecommerce/media/AV.000901_FEATURE_58311.jpg'),
		(3,'https://hc.com.vn/i/ecommerce/media/AV.000901_FEATURE_58312.jpg'),
		(3,'https://hc.com.vn/i/ecommerce/media/AV.000901_FEATURE_58314.jpg'),
		(3,'https://hc.com.vn/i/ecommerce/media/AV.000901_FEATURE_58315.jpg'),
		(3,'https://hc.com.vn/i/ecommerce/media/AV.000901_FEATURE_58316.jpg'),
		(3,'https://hc.com.vn/i/ecommerce/media/AV.000901_FEATURE_58317.jpg'),
		(4,'https://hc.com.vn/i/ecommerce/media/00033679_FEATURE_38665.jpg'),
		(4,'https://hc.com.vn/i/ecommerce/media/00033679_FEATURE_38666.jpg'),
		(4,'https://hc.com.vn/i/ecommerce/media/00033679_FEATURE_38667.jpg'),
		(5,'https://hc.com.vn/i/ecommerce/media/00033682_FEATURE_38654.jpg'),
		(5,'https://hc.com.vn/i/ecommerce/media/00033682_FEATURE_53358.jpg'),
		(5,'https://hc.com.vn/i/ecommerce/media/00033682_FEATURE_55352.jpg'),
		(5,'https://hc.com.vn/i/ecommerce/media/00033682_FEATURE_55353.jpg'),
		(5,'https://hc.com.vn/i/ecommerce/media/00033682_FEATURE_55354.jpg'),
		(5,'https://hc.com.vn/i/ecommerce/media/00033682_FEATURE_55355.jpg'),
		(5,'https://hc.com.vn/i/ecommerce/media/00033682_FEATURE_55356.jpg'),
		(5,'https://hc.com.vn/i/ecommerce/media/00033682_FEATURE_55357.jpg'),
		(5,'https://hc.com.vn/i/ecommerce/media/00033682_FEATURE_55358.jpg'),
		(6,'https://hc.com.vn/i/ecommerce/media/AV.000910_FEATURE_58230.jpg'),
		(6,'https://hc.com.vn/i/ecommerce/media/AV.000910_FEATURE_58231.jpg'),
		(6,'https://hc.com.vn/i/ecommerce/media/AV.000910_FEATURE_58232.jpg'),
		(6,'https://hc.com.vn/i/ecommerce/media/AV.000910_FEATURE_58233.jpg'),
		(6,'https://hc.com.vn/i/ecommerce/media/AV.000910_FEATURE_58234.jpg'),
		(6,'https://hc.com.vn/i/ecommerce/media/AV.000910_FEATURE_58235.jpg'),
		(6,'https://hc.com.vn/i/ecommerce/media/AV.000910_FEATURE_58236.jpg'),
		(7,'https://hc.com.vn/i/ecommerce/media/AV.001456_FEATURE_67498.jpg'),
		(7,'https://hc.com.vn/i/ecommerce/media/AV.001456_FEATURE_67499.jpg'),
		(7,'https://hc.com.vn/i/ecommerce/media/AV.001456_FEATURE_67500.jpg'),
		(7,'https://hc.com.vn/i/ecommerce/media/AV.001456_FEATURE_67501.jpg'),
		(7,'https://hc.com.vn/i/ecommerce/media/AV.001456_FEATURE_67502.jpg'),
		(7,'https://hc.com.vn/i/ecommerce/media/AV.001456_FEATURE_67503.jpg'),





insert into MoTaSp(SanPhamID,ID,image,TieuDe)
	values(1,1, 'https://hc.com.vn/i/ecommerce/media/AV.001708_FEATURE_67662.jpg',N'Smart Tivi LG NanoCell 8K 55 inch 55NANO95TNA'),
		(2,2,'',N'Smart Tivi LG NanoCell 8K 75 inch 75NANO95TPA'),
		(3,3,'',N'Smart Tivi QLED Samsung 8K 75 inch QA75Q950TSKXXV'),
		(4,4,'https://hc.com.vn/i/ecommerce/media/ckeditor_1947987.jpg',N'Smart Tivi QLED Samsung 8K 75 inch QA75Q900R'),
		(5,5,'https://hc.com.vn/i/ecommerce/media/ckeditor_1947450.jpg',''),
		(6,6,'',N'Smart Tivi QLED Samsung 8K 75 inch QA75Q800TAKXXV'),
		(7,7,'',N'Smart Tivi LG NanoCell 8K 75 inch 75NANO95TNA'),



insert into SubMoTa(MoTaSpID,TieuDe,NoiDung,Image,NoiDungThem,ImageThem)
	values(1, N'Thiết kế sang trọng, đẳng cấp',N'Smart Tivi LG NanoCell 8K 55 inch 55NANO95TNA sở hữu thiết kế hiện đại, sang trọng, tinh tế đến từng đường nét. Đường viền Nano Bezel tinh gọn, siêu mảnh tối ưu vùng hiển thị mang lại trải nghiệm khác biệt, đồng thời hòa hợp tôn thêm vẻ đẹp cho mọi không gian nội thất. Kích thước lớn lên tới 55 inch thích hợp với những buổi tụ họp giải trí cùng gia đình, bạn bè trong những căn phòng rộng rãi như phòng khách, phòng họp.','https://hc.com.vn/i/ecommerce/media/ckeditor_3064317.jpg','',''),
		(1, N'Hình ảnh sắc nét, chất lượng hoàn hảo với độ phân giải 8K',N'Khám phá những khung hình với chất lượng hình ảnh siêu nét trên Smart Tivi LG 8K 55NANO95TNA nhờ số điểm ảnh lên đến 33 triệu nhiều hơn gấp 4 lần so với độ phân giải 4K.','https://hc.com.vn/i/ecommerce/media/ckeditor_2872158.jpg','',''),
		(1,N'Màu sắc thuần khiết và chính xác nhờ công nghệ NanoCell',N'Tivi LG NanoCell sử dụng các hạt nano siêu nhỏ để hoạt động như các bộ lọc màu hấp thụ ánh sáng dư thừa đồng thời giúp giảm hiện tượng sai lệch màu sắc khi hiển thị trên màn hình, đảm bảo độ sáng cao và tăng cường độ tinh khiết màu sắc, cho trải nghiệm từng khung hình rực rỡ, chân thật và sống động hơn. Đồng thời, TV LG NanoCell 8K 55 inch 55NANO95TNA  còn được công nghệ Billion Rich Colors hỗ trợ mang lại phổ màu rộng và đa dạng.','https://hc.com.vn/i/ecommerce/media/ckeditor_2872163.jpg',N'Hơn thế nữa, TV LG NanoCell đã nhận được chứng nhận “Không có nguy cơ LED quang sinh học” từ Underwriters Laboratories (UL), đảm bảo đôi mắt của bạn được bảo vệ tránh ánh sáng có hại phát ra.',''),
		(1,N'Đáp ứng mọi kết nối, dễ dàng sẻ chia','Tivi LG 55NANO95TNA được trang bị nhiều cổng kết nối khác nhau như: USB, HDMI, AV composite… giúp người dùng dễ dàng chia sẻ và thưởng thức những nội dung giải trí yêu thích từ các thiết bị khác trên màn hình lớn của tivi. Kết nối cổng LAN, Wifi để khám phá kho ứng dụng, giải trí khổng lồ từ internet. Hay tận hưởng âm thanh sống động hơn với các dàn âm thanh chuyên dụng qua cổng Optical. Kết nối Bluetooth cho phép tạo hiệu ứng âm thanh vòm 4.0 bằng cách kết nối với 2 loa bluetooth.','https://hc.com.vn/i/ecommerce/media/ckeditor_2872165.jpg',N'Đặc biệt, trình chiếu màn hình điện thoại lên tivi qua tính năng AirPlay 2 (iPhone) hoặc Screen Mirroring (điện thoại Android) hay điều khiển tivi bằng điện thoại thông qua ứng dụng LG TV Plus đều vô cùng tiện lợi.',''),
		(2,N'Thiết kế đẳng cấp nâng tầm không gian sống tiện nghi',N'Smart Tivi LG NanoCell 8K 75 inch 75NANO95TPA sở hữu phong cách thiết kế đẳng cấp, kiểu dáng đẹp kết hợp với tông màu đen thanh lịch, cuốn hút từ mọi góc nhìn, phù hợp với mọi không gian nội thất trong nhà bạn. Bạn có thể đặt tivi lên kệ hoặc treo tường vừa tiết kiệm không gian lại tạo điểm nhấn nổi bật cho căn phòng thêm phần tinh tế, sang trọng.','https://hc.com.vn/i/ecommerce/media/ckeditor_3183821.jpg',N'Không chỉ đơn thuần là thiết bị giải trí thông thường tivi LG còn mang tính thẩm mỹ cao, trang trí cho không gian nội thất nhà bạn thêm phần sang trọng, tiện nghi, nâng cấp trải nghiệm sống và đáp ứng linh hoạt nhu cầu của người dùng.','https://hc.com.vn/i/ecommerce/media/ckeditor_3183809.jpg'),
		(2,N'Độ phân giải 8K cho màu sắc tinh khiết, hình ảnh chân thực',N'LG luôn mang đến sự bất ngờ thú vị cho người dùng, thể hiện sự khác biệt điểm nổi bật ở mỗi dòng tivi mới ra mắt. Với dòng tivi LG NanoCell NANO95TPA hình ảnh và màu sắc của tivi đã được nâng cấp lên độ phân giải 8K, màu sắc được hiển thị tinh khiết chính xác hơn, chất lượng sắc nét hơn nâng tầm trải nghiệm xem trở nên chân thực nhất. ','https://hc.com.vn/i/ecommerce/media/ckeditor_3141215.gif','',''),
		(2,N'Bộ xử lý α9 Gen4 AI 8K nâng cao chất lượng hình ảnh và âm thanh',N'Hình ảnh sẽ giảm nhiễu đáng kể, tăng cường độ sắc nét và độ chi tiết hình ảnh khi tivi được tích hợp bộ xử lý thông minh α9 Gen4 AI 8K. Âm thanh được tối ưu hóa theo từng thể loại âm thanh bằng cách xác định giọng nói, không gian, hiệu ứng và tần số để điều chỉnh âm thanh phù hợp.','https://hc.com.vn/i/ecommerce/media/ckeditor_3183813.jpg','','https://hc.com.vn/i/ecommerce/media/ckeditor_3183811.jpg'),
		(2,N'Công nghệ NanoCell cho màu sắc thuần khiết, hình ảnh chân thực tự nhiên hơn',N'Smart Tivi LG sở hữu công nghệ NanoCell sử dụng các hạt nano để lọc màu, lọc bỏ các màu nhạt, chỉ những màu sắc tinh khiết, chính xác mới được hiển thị trên màn hình, tạo độ thuần khiết cho màu sắc mang đến cho người xem những hình ảnh chất lượng chân thật nhất như ngoài đời thực.','https://hc.com.vn/i/ecommerce/media/ckeditor_3141219.gif','',''),
		(2,N'Công nghệ Dolby Vision IQ & Dolby Atmos hiển thị màu sắc rõ nét, âm thanh sống động hơn',N'Công nghệ Dolby Vision IQ & Dolby Atmos được trang bị trên tivi LG giúp tăng độ tương phản, cân bằng hình ảnh, màu sắc chính xác, hình ảnh sống động, thật như cuộc sống. Dolby Atmos mang đến trải nghiệm âm thanh sống động, giúp tận hưởng trọn vẹn mọi nội dung khi xem.','https://hc.com.vn/i/ecommerce/media/ckeditor_3141204.jpg','',''),
		(2,N'Nâng cấp hình ảnh lên chất lượng lên HDR nhờ công nghệ HDR 10 Pro',N'Tivi LG NanoCell mang đến chất lượng hình ảnh HDR được tối ưu nhờ công nghệ HDR 10 Pro cho hình ảnh sắc nét, chân thực hơn người dùng có thể thưởng thức trọn vẹn mọi nội dung với độ phân giải cao như ngoài đời thực.','https://hc.com.vn/i/ecommerce/media/ckeditor_3141206.jpg','',''),
		(2,N'Trải nghiệm thế giới game giải trí sống động, hình ảnh mượt mà',N'Tivi LG mang đến cho người dùng trải nghiệm chơi game thực sự thú vị. Từ những khung cảnh hang động tối tăm đến những cảnh tươi sáng màu sắc vẫn được hiển thị sắc nét, sống động nhất nhờ công nghệ chơi game đám mây và tự động điều chỉnh hình ảnh chất lượng cao.','https://hc.com.vn/i/ecommerce/media/ckeditor_3141789.PNG','',''),
		(2,N'Công nghệ Full Array Dimming tối ưu hóa độ tương phản ',N'Nhờ công nghệ Full Array Dimming tivi LG sẽ được tối ưu hóa độ tương phản và màu đen bằng cách điều chỉnh riêng biệt đèn LED cho người dùng trải nghiệm xem hấp dẫn với hình ảnh chất lượng chi tiết hơn.','https://hc.com.vn/i/ecommerce/media/ckeditor_3183814.jpg','',''),
		(2,N'AirPlay 2 - Chiếu màn hình điện thoại lên tivi',N'Smart Tivi LG NanoCell 8K 75 inch 75NANO95TPA được tích hợp tính năng chiếu màn hình điện thoại lên tivi: Trình chiếu nội dung hình ảnh, video từ điện thoại, máy tính bảng lên màn ảnh rộng 75 inch cho mọi người cùng thưởng thức.','https://hc.com.vn/i/ecommerce/media/ckeditor_3183812.jpg','',''),
		(2,N'Hỗ trợ nhiều cổng kết nối mở rộng thế giới giải trí',N'Smart Tivi LG NanoCell 8K 75 inch 75NANO95TPA được trang bị nhiều cổng kết nối như: LAN, Wifi không dây, USB, HDMI...cho phép bạn khai thác những chương trình giải trí từ nhiều nguồn khác nhau mang đến thế giới Internet rộng lớn và đa dạng.','','',''),
		(3,N'Màn hình vô cực cho không gian giải trí vô hạn',N'Smart Tivi QLED Samsung 8K 75 inch QA75Q950TSKXXV là dòng tivi QLED 8K sở hữu màn hình vô cực kết hợp cạnh viền siêu mỏng tạo nên một tuyệt tác, điểm nhấn ấn tượng cho không gian nội thất nhà bạn mang đến cho người dùng thế giới giải trí hấp dẫn, cuốn hút thông qua màn hình 8K một cách chân thực.','https://hc.com.vn/i/ecommerce/media/ckeditor_2703616.jpg',N'Màn hình 75 inch, tivi Samsung sẽ là sự lựa chọn lý tưởng bài trí trong những không gian rộng như: phòng khách, hội trường, phòng hội nghị…',''),
		(3,N'Độ phân giải 8K cho khung hình sắc nét vượt trội',N'Smart Tivi Samsung được trang bị độ phân giải 8K cho hình ảnh hiển thị sắc nét gấp 4 lần 4K thông thường cho phép bạn được trải nghiệm các chương trình giải trí thêm thú vị, hình ảnh chân thật hơn. ','https://hc.com.vn/i/ecommerce/media/ckeditor_2703601.jpg','',''),
		(3,N'Công nghệ Quantum Dot hiển thị 100% dải màu sắc cho hình ảnh sống động như thật','Samsung mang đến cho người dùng một trải nghiệm mới chính là công nghệ chấm lượng tử, công nghệ này cho phép tivi có thể đạt độ sáng lên đến 4000 nit giúp hiển thị hình ảnh HDR được sắc nét và chân thực hơn. Hơn nữa, tivi còn được tích hợp thêm công nghệ Quantum HDR cải thiện độ chính xác màu sắc, tối ưu độ tương phản và điều chỉnh và tạo ra đúng loại ánh sáng phù hợp.','https://hc.com.vn/i/ecommerce/media/ckeditor_2703600.jpg','',''),
		(3,N'Bộ xử lý Quantum 8K tối ưu hóa khả năng hiển thị hình ảnh chất lượng hơn',N'Tivi Samsung sở hữu bộ xử lý Quantum 8K nâng cấp hình ảnh có chất lượng không phải 8K lên gần chuẩn 8K nhất, với bộ xử lý Quantum Processor 8K tích hợp trí thông minh nhân tạo AI cho bạn những trải nghiệm các chương trình giải trí, tin tức, thể thao...chân thực nhất. ','https://hc.com.vn/i/ecommerce/media/ckeditor_2703603.jpg','',''),
		(3,N'Công nghệ đèn nền Direct Full Array 32x tối ưu độ sáng tối rõ nét, chi tiết',N'Nhờ công nghệ đèn nền Direct Full Array, vùng đèn nền sẽ tập trung điều khiển chính xác độ sáng tối của màn hình, tối ưu hoàn hảo sắc đen sâu thẳm, sắc sáng rực rỡ hơn cho hình ảnh sắc nét, chi tiết hơn.','https://hc.com.vn/i/ecommerce/media/ckeditor_2703602.jpg','',''),
		(3,N'Chế độ hình nền Ambient Mode cài đặt màn hình theo sở thích',N'Bạn sẽ được chiêm ngưỡng những tuyệt nghệ thuật ngay tại nhà mà không cần đi xem triển lãm nhờ chế độ Ambient Mode cho phép tivi hiển thị những hình ảnh đẹp theo chủ đề, hình cá nhân, âm nhạc, thời tiết, mô phỏng lại màu sơn của bức tường, tranh phong cảnh…','https://hc.com.vn/i/ecommerce/media/ckeditor_2703606.jpg','',''),
		(3,N'Công nghệ Object Tracking Sound trải nghiệm âm thanh vòm sống động',N'Ngoài công nghệ Dolby Digital Plus, smart Tivi Samsung được ứng dụng công nghệ Object Tracking Sound tiên tiến, trang bị thêm loa ở viền trên, 2 bên, tổng công suất loa lên đến 70W, mang đến hệ thống âm thanh vòm lan tỏa, cho phép bạn thỏa sức tận hưởng âm thanh chuẩn 3D chân thực qua từng cảnh quay.','https://hc.com.vn/i/ecommerce/media/ckeditor_2703605.jpg','',''),
		(3,N'Hệ điều hành Tizen OS giao diện mượt mà, kho ứng dụng phong phú, đa dạng',N'Smart Tivi QLED Samsung 8K 75 inch QA75Q950TSKXXV có giao diện sử dụng mượt mà, ổn định, thao tác nhanh chóng dễ dàng thích nghi cùng nhiều tiện ích hỗ trợ người dùng trong quá trình sử dụng thêm hiệu quả.','https://hc.com.vn/i/ecommerce/media/ckeditor_2703607.jpg',N'Hơn nữa, tivi còn được trang bị kho ứng dụng phong phú các thể loại phổ biến như Netflix, Fim+, FPT Play, Clip TV, Zing TV, Nhaccuatui, Spotify, Apple TV, My TV, Youtube,... mang đến không gian giải trí bất tận.',''),
		(3,N'One Remote đa nhiệm điều khiển thông minh, tìm kiếm bằng giọng nói tiện dụng',N'Thay bằng việc sử dụng điều khiển chính, One Remote đa nhiệm sẽ giúp bạn tìm kiếm các nội dung giải trí một cách dễ dàng. Ngoài ra, bạn có thể tìm kiếm giọng nói có hỗ trợ tiếng Việt trên Youtube rất tiện dụng với người già và trẻ nhỏ. ','https://hc.com.vn/i/ecommerce/media/ckeditor_2703608.jpg','',''),
		(3,N'Hỗ trợ cổng kết nối đa dạng',N'Smart Tivi Samsung sở hữu các cổng kết nối: HDMI, USB, Optical giúp bạn chia sẻ các dữ liệu hình ảnh, âm thanh từ đầu đĩa, laptop, dàn máy... lên tivi một cách dễ dàng.','https://hc.com.vn/i/ecommerce/media/ckeditor_2703611.jpg','',''),
		(4,N'QLED Samsung thiết kế hoàn hảo đến từng chi tiết',N'Smart Tivi 75Q900R QLED Samsung 8K 75 inch sở hữu thiết kế hoàn hảo với màn hình siêu mỏng tạo cảm giác ấn tượng cho người dùng với cái nhìn lần đầu tiên, hình ảnh sắc nét bao trùm ở mọi góc độ nhìn mang đến sự sang trọng và nghệ thuật cho không gian căn phòng.','https://hc.com.vn/i/ecommerce/media/ckeditor_1947988.jpg',N'Với màn hình rộng 75 inch lớn QA75Q900R 8K TV Smart vượt trội cho phép người dùng trải nghiệm một cách chân thực nhất, dễ dàng truyền tải thông tin từng cung cập cảm xúc đến với người xem, thích hợp bố trí vào không gian nội thất rộng như phòng họp, phòng khách....',''),
		(4,N'Độ phân giải 8K QA75Q900RBKXXV Samsung',N'Chất lượng hình ảnh chân thực bạn chưa từng thấy Samsung QLED 8K 75Q900R. Trên một khung hình sống động, từng chi tiết nhỏ nhất được tái tạo tỉ mỉ đến khó tin, kết hợp với độ phân giải đỉnh cao, QLED 8K Q900R như bao trùm mọi giác quan, biến từng thước phim trở nên chân thật như chính bạn đang chứng kiến.','https://hc.com.vn/i/ecommerce/media/ckeditor_1947990.jpg',N'QLED 8K 75Q900R Tivi Samsung được trang bị độ phân giải 8K với 33 triệu điểm ảnh gấp 4 lần 4K UHD, 16 lần FHD mang đến cho người dùng những hình ảnh chất lượng khi thưởng thức những bộ phim hay những chương trình giải trí hấp dẫn. Samsung QLED 8K truyền tải trọn vẹn chuỗi hình ảnh sắc nét và tái tạo mọi sắc màu rực rỡ chưa từng có trước đây.',''),
		(4,N'Cảm nhận hình ảnh thực tế trọn vẹn hơn',N'Samsung QA75Q900RBKXXV mang đến những hình ảnh sống động, rõ nét như thật trên màn hình lớn cho bạn thấy cả những chi tiết nhỏ nhất trong mỗi cảnh quay, giúp bạn cảm nhận thực tế nhất.','https://hc.com.vn/i/ecommerce/media/ckeditor_1947994.jpg','',''),
		(4,N'Công nghệ chấm lượng tử Quantum Processor 8K',N'Cùng với độ phân giải 8K, điểm nổi bật của chiếc TV QLED 8K Samsung 75Q900R 75 inch chính là công nghệ Quantum Processor thế hệ mới mang đến màu sắc hoàn hảo, các cảnh quay chân thực cho người dùng trải nghiệm ấn tượng nhất.','https://hc.com.vn/i/ecommerce/media/ckeditor_1947989.jpg','',''),
		(4,N'Công nghệ đèn nền Direct Full Array 16X','Chiêm ngưỡng sắc màu thuần khiết chưa từng thấy. Với khả năng phân tích và kiểm soát đèn nền trong từng khung hình trình chiếu từ công nghệ đèn nền Direct Full Array 16X 8K 75Q900R QLED, QLED truyền tải ấn tượng các chi tiết hình ảnh phức tạp nhất với sắc đen sâu thẳm, giảm thiểu hiện tượng hở sáng, tạo nên độ sâu đáng kinh ngạc cho nội dung hiển thị.','https://hc.com.vn/i/ecommerce/media/ckeditor_2851537.jpg','',''),
		(4,N'Công nghệ Quantum HDR 4000 nits Smart TV Samsung QA75Q900RBKXXV',N'Công nghệ Quantum HDR 4000 nits với khả năng tối ưu hóa dải tương phản HDR theo mỗi phân cảnh khác nhau, tái hiện tỉ mỉ từng chi tiết nhỏ nhất và tạo nên chất lượng hình ảnh đỉnh cao theo đúng ý từ nhà sản xuất. Hoàn hảo từng sắc màu cuộc sống ngay trong chính không gian bạn.','https://hc.com.vn/i/ecommerce/media/ckeditor_2851691.jpg','',''),
		(4,N'Công nghệ Ultra Viewing Angle',N'Tận hưởng nội dung hiển thị đẹp mắt tại mọi vị trí với công nghệ Ultra Viewing Angle ngay tại TV QLED QA75Q900R giúp giảm thiểu tối đa sự rò rỉ ánh sáng, tập trung và phân bổ đều luồng sáng trên bảng điều khiển cho bạn thoải mái tận hưởng sắc màu trung thực và đồng nhất tại mọi vị trí trong không gian.','https://hc.com.vn/i/ecommerce/media/ckeditor_2851696.jpg','',''),
		(4,N'Âm thanh sắc nét đến từng cảnh quay',N'QLED 8k có khả năng phân tích và tự động tối ưu hóa âm thanh chi tiết cho từng cảnh quay giúp bạn có những cảm nhận chân thực nhất nội dung đang xem thật như cuộc sống.','https://hc.com.vn/i/ecommerce/media/ckeditor_1947991.jpg','',''),
		(4,N'Smart View  - Điều khiển và chia sẻ hình ảnh lên tivi bằng điện thoại',N'Với ứng dụng Samsung Smartview QA75Q900RBKXXV thông minh, bạn có thể điều khiển tivi bằng chiếc điện thoại của mình hay chỉ đơn giản là chiếu hình ảnh từ điện thoại lên tivi một cách dễ dàng bằng Screen Mirroring.','https://hc.com.vn/i/ecommerce/media/ckeditor_1947993.jpg','',''),
		(4,N'Kết nối đa dạng',N'Chắc chắn khi sở hữu một chiếc tivi QLED Samsung QA75Q900RBKXXV thông minh bạn sẽ được trang bị đầy đủ các cổng kết nối như Wifi, HDMI, USB, LAN… để bạn có thể kết nối tivi với các thiết bị bên ngoài như loa, đầu đĩa và laptop, điện thoại…','Chắc chắn khi sở hữu một chiếc tivi QLED Samsung QA75Q900RBKXXV thông minh bạn sẽ được trang bị đầy đủ các cổng kết nối như Wifi, HDMI, USB, LAN… để bạn có thể kết nối tivi với các thiết bị bên ngoài như loa, đầu đĩa và laptop, điện thoại…','',''),
		(5,N'QLED Samsung thiết kế hoàn hảo đến từng chi tiết',N'Tận hưởng trọn vẹn sắc màu cuộc sống trên một màn hình lớn và sắc nét vượt trội. Kết hợp với chất lượng hiển thị hoàn hảo, QA82Q900 QLED TV thế hệ mới mang đến cho bạn một trải nghiệm xem sống động, chân thực như đang diễn ra trước mắt.','https://hc.com.vn/i/ecommerce/media/ckeditor_1947451.jpg',N'Tivi QLED Samsung QA82Q900R sở hữu thiết kế hoàn hảo, hình ảnh sắc nét, màn hình rộng 82 inch cho phép người dùng trải nghiệm một cách chân thực nhất.',''),
		(5,N'Độ phân giải 8K 82 inch QLED QA82Q900RBKXXV',N'Mở ra kỷ nguyên chất lượng hình ảnh chân thực bạn chưa từng thấy. Trên một khung hình sống động, từng chi tiết nhỏ nhất được tái tạo tỉ mỉ đến khó tin, kết hợp với độ phân giải đỉnh cao, QLED 8K 82Q900R như bao trùm mọi giác quan, biến từng thước phim trở nên chân thật như chính bạn đang chứng kiến.','https://hc.com.vn/i/ecommerce/media/ckeditor_1947453.jpg',N'Tivi Samsung QA82Q900R 82 inch được trang bị độ phân giải 8K với 33 triệu điểm ảnh gấp 4 lần 4K UHD, 16 lần FHD mang đến cho người dùng những hình ảnh chất lượng khi thưởng thức những bộ phim hay những chương trình giải trí hấp dẫn.',''),
		(5,N'8K Smart QA82Q900RBKXXV - Nâng cấp AI lên 8K',N'QLED QA82Q900R TV Samsung  được tích hợp công nghệ trí thông minh nhân tạo AI giúp nâng cấp và hiển thị sắc nét mọi nội dung hình ảnh với chất lượng gần chuẩn 8K nhất làm giảm thiểu tình trạng nhiễu hạt, tái tạo hoàn hảo từng chi tiết phức tạp.','https://hc.com.vn/i/ecommerce/media/ckeditor_2850991.jpg','',''),
		(5,N'Công nghệ Ultra Viewing Angle',N'Tận hưởng nội dung hiển thị đẹp mắt tại mọi vị trí với công nghệ Ultra Viewing Angle Samsung 82Q900R giúp giảm thiểu tối đa sự rò rỉ ánh sáng, tập trung và phân bổ đều luồng sáng trên bảng điều khiển cho bạn thoải mái tận hưởng sắc màu trung thực và đồng nhất tại mọi vị trí trong không gian.','','',''),
		(5,N'Cảm nhận hình ảnh thực tế trọn vẹn hơn',N'QLED TV QA82Q900R Samsung 8K tối ưu độ phân giải vượt trội tạo nên độ sâu ảnh đáng kinh ngạc và khả năng hiển thị hoàn hảo từng chi tiết phức tạp, mang đến khung hình 8K thật như đang diễn ra trước mắt bạn.','https://hc.com.vn/i/ecommerce/media/ckeditor_1947457.jpg',N'Samsung QA82Q900RBKXXV mang đến những hình ảnh sống động, rõ nét như thật trên màn hình lớn cho bạn thấy cả những chi tiết nhỏ nhất trong mỗi cảnh quay, giúp bạn cảm nhận thực tế nhất.',''),
		(5,N'Công nghệ chấm lượng tử Quantum Processor 8K TV 82Q900R',N'Cùng với độ phân giải 8K, điểm nổi bật của chiếc QA82Q900R Tivi Samsung 82 inch chính là công nghệ Quantum Processor thế hệ mới mang đến màu sắc hoàn hảo, các cảnh quay chân thực cho người dùng trải nghiệm ấn tượng nhất.','https://hc.com.vn/i/ecommerce/media/ckeditor_1947452.jpg','',''),
		(5,N'Công nghệ đèn nền Direct Full Array 16X 82Q900R Samsung Tivi QLED',N'Chiêm ngưỡng sắc màu thuần khiết chưa từng thấy ngay trên TV Samsung QA82Q900RBKXXV QLED 8K. Với khả năng phân tích và kiểm soát đèn nền trong từng khung hình trình chiếu từ công nghệ đèn nền Direct Full Array 16X, QLED truyền tải ấn tượng các chi tiết hình ảnh phức tạp nhất với sắc đen sâu thẳm, giảm thiểu hiện tượng hở sáng, tạo nên độ sâu đáng kinh ngạc cho nội dung hiển thị.','https://hc.com.vn/i/ecommerce/media/ckeditor_2850941.jpg','',''),
		(5,N'Công nghệ Quantum HDR 4000 nits',N'Công nghệ Quantum HDR 4000 nits QLED QA82Q900R với khả năng tối ưu hóa dải tương phản HDR theo mỗi phân cảnh khác nhau, tái hiện tỉ mỉ từng chi tiết nhỏ nhất và tạo nên chất lượng hình ảnh đỉnh cao theo đúng ý từ nhà sản xuất. Hoàn hảo từng sắc màu cuộc sống ngay trong chính không gian bạn.','','',''),
		(5,N'TV 82Q900R 82 inch Samsung - Chế độ Ambient Mode ',N'Ngay tại Tivi QA82Q900R Samsung Smart - Biến QLED thành tác phẩm nghệ thuật ngay khi không hoạt động với chế độ hình nền Ambient Mode nhận diện màu sắc, hoa văn trên tường để biến đổi tương thích với không gian xung quanh. Sáng tạo bất tận màn hình chờ thành kiệt tác nghệ thuật hay trung tâm tin tức ngay trong chính căn phòng bạn.','https://hc.com.vn/i/ecommerce/media/ckeditor_2851004.jpg','',''),
		(5,N'One Remote – Điều khiển thông minh',N'Với chiếc điều khiển thông minh tivi Samsung QA82Q900RBKXXV cho phép bạn dễ dàng thao tác tìm kiếm các chương trình trên tivi, chỉ cần một chiếc remote là có thể điều khiển mọi thiết bị như: đầu đĩa, máy chơi game, dàn âm thanh... khi kết nối với tivi qua HDMI. Ngoài ra, QA82Q900R Smart 82 inch Tivi còn hỗ trợ tìm kiếm nội dung qua giọng nói.','https://hc.com.vn/i/ecommerce/media/ckeditor_1947458.jpg','',''),
		(6,N'Kiểu dáng tinh tế, màn hình phẳng không viền 4 cạnh ấn tượng',N'Smart Tivi QLED Samsung 8K 75 inch QA75Q800TAKXXV là dòng tivi QLED 8K sở hữu màn hình không viền 4 cạnh tinh tế tạo điểm nhấn ấn tượng cho không gian nội thất nhà bạn mang đến cho người dùng thế giới giải trí hấp dẫn, cuốn hút thông qua màn hình 8K một cách chân thực.','https://hc.com.vn/i/ecommerce/media/ckeditor_2709219.jpg',N'Màn hình 75 inch, tivi Samsung sẽ là sự lựa chọn lý tưởng bài trí trong những không gian rộng như: phòng khách, hội trường, phòng hội nghị…',''),
		(6,N'Độ phân giải 8K cho khung hình sắc nét vượt trội',N'Smart Tivi Samsung được trang bị độ phân giải 8K cho hình ảnh hiển thị sắc nét gấp 4 lần 4K thông thường cho phép bạn được trải nghiệm các chương trình giải trí thêm thú vị, chân thực đến từng chi tiết nhỏ.','https://hc.com.vn/i/ecommerce/media/ckeditor_2709118.jpg','',''),
		(6,N'Màn hình chấm lượng tử Quantum Dot 100% dải màu sắc cho hình ảnh sống động như thật',N'Smart Tivi QLED Samsung 8K 75 inch QA75Q800T sở hữu màn hình chấm lượng tử, công nghệ này cho phép tivi hiển thị 100% dải màu sắc, đem đến những hình ảnh với màu sắc chân thật nhất qua từng khung hình, cảnh quay thú vị.. Hơn nữa, tivi còn được tích hợp thêm công nghệ Quantum HDR cải thiện độ chính xác màu sắc, tối ưu độ tương phản và điều chỉnh và tạo ra đúng loại ánh sáng phù hợp.','https://hc.com.vn/i/ecommerce/media/ckeditor_2709120.jpg','',''),
		(6,N'Bộ xử lý Quantum 8K tối ưu hóa khả năng hiển thị hình ảnh chất lượng hơn',N'Tivi Samsung sở hữu bộ xử lý Quantum 8K nâng cấp hình ảnh có chất lượng không phải 8K lên gần chuẩn 8K nhất, với bộ xử lý Quantum Processor 8K tích hợp trí thông minh nhân tạo AI cho bạn những trải nghiệm các chương trình giải trí, tin tức, thể thao...chân thực nhất.','https://hc.com.vn/i/ecommerce/media/ckeditor_2709121.jpg','',''),
		(6,N'Adaptive Picture - Tự động điều chỉnh độ sáng phù hợp với ánh sáng bên ngoài',N'Adaptive Picture là tính năng tự động điều chỉnh độ sáng của màn hình phù hợp với ánh sáng bên ngoài môi trường xem, truyền tải đúng màu sắc nội dung của hình ảnh bất kể bạn đang xem trong không gian nhiều ánh sáng hay thiếu sáng.','https://hc.com.vn/i/ecommerce/media/ckeditor_2709124.jpg','',''),
		(6,N'Công nghệ đèn nền Direct Full Array tối ưu độ sáng tối rõ nét, chi tiết',N'Nhờ công nghệ đèn nền Direct Full Array, vùng đèn nền sẽ tập trung điều khiển chính xác độ sáng tối của màn hình, tối ưu hoàn hảo sắc đen sâu thẳm, sắc sáng rực rỡ hơn cho hình ảnh sắc nét, chi tiết hơn.','https://hc.com.vn/i/ecommerce/media/ckeditor_2709125.jpg','',''),
		(6,N'Công nghệ Ultra Viewing Angle cho khung hình chất lượng ở mọi góc nhìn',N'Nhờ công nghệ Ultra Viewing Angle cho bạn thưởng thức các chương trình giải trí với màu sắc chân thực, không bị thay đổi khi ngồi ở các vị trí khác nhau, kể cả góc nhìn lệch mà không có hiện tượng nhiễu màu hay bị lóa sáng.','https://hc.com.vn/i/ecommerce/media/ckeditor_2709122.jpg','',''),
		(6,N'Công nghệ Real Game Enhancer chơi game thú vị',N'Smart Tivi Samsung 8K 75 inch QA75Q800T được trang bị thêm công nghệ Real Game Enhancer cho phép người dùng được trải nghiệm game giải trí mượt mà, thú vị hơn nhờ nâng cấp hình ảnh chất lượng không lo hình ảnh bị nhiễu hay cuộc chơi bị gián đoạn.','https://hc.com.vn/i/ecommerce/media/ckeditor_2709123.jpg','',''),
		(6,N'Công nghệ Object Tracking Sound trải nghiệm âm thanh vòm sống động',N'Ngoài công nghệ Dolby Digital Plus, smart tivi Samsung QA75Q800T được ứng dụng công nghệ Object Tracking Sound tiên tiến, trang bị thêm loa ở viền trên, 2 bên, tổng công suất loa lên đến 70W, mang đến hệ thống âm thanh vòm lan tỏa, cho phép bạn thỏa sức tận hưởng âm thanh chuẩn 3D chân thực qua từng cảnh quay.','https://hc.com.vn/i/ecommerce/media/ckeditor_2709128.jpg','',''),
		(6,N'Tính năng Multi View chia đôi màn hình, xem cùng lúc 2 nội dung',N'Multi View cho phép chia đôi màn hình tivi, một bên hiển thị nội dung bạn đang xem trên tivi, một bên sẽ phản chiếu màn hình điện thoại cùng một lúc theo dõi 2 nội dung rất tiện dụng. ','https://hc.com.vn/i/ecommerce/media/ckeditor_2709126.jpg','',''),
		(6,N'Hệ điều hành Tizen OS giao diện mượt mà, kho ứng dụng phong phú, đa dạng',N'Smart Tivi QLED Samsung 8K 75 inch QA75Q800TAKXXV có giao diện sử dụng mượt mà, ổn định, thao tác nhanh chóng dễ dàng thích nghi cùng nhiều tiện ích hỗ trợ người dùng trong quá trình sử dụng thêm hiệu quả.','https://hc.com.vn/i/ecommerce/media/ckeditor_2709132.jpg',N'Hơn nữa, tivi còn được trang bị kho ứng dụng phong phú các thể loại phổ biến như Netflix, Fim+, FPT Play, Clip TV, Zing TV, Nhaccuatui, Spotify, Apple TV, My TV, Youtube,... mang đến không gian giải trí bất tận.',''),
		(6,N'One Remote đa nhiệm điều khiển thông minh, tìm kiếm bằng giọng nói tiện dụng',N'Thay bằng việc sử dụng điều khiển chính, One Remote đa nhiệm sẽ giúp bạn tìm kiếm các nội dung giải trí một cách dễ dàng. Ngoài ra, bạn có thể tìm kiếm giọng nói có hỗ trợ tiếng Việt trên Youtube rất tiện dụng với người già và trẻ nhỏ.','https://hc.com.vn/i/ecommerce/media/ckeditor_2709133.jpg','',''),
		(7,N'Thiết kế sang trọng, đẳng cấp',N'Smart Tivi LG NanoCell 8K 75 inch 75NANO95TNA sở hữu thiết kế hiện đại, sang trọng, tinh tế đến từng đường nét. Đường viền Nano Bezel tinh gọn, siêu mảnh tối ưu vùng hiển thị mang lại trải nghiệm khác biệt, đồng thời hòa hợp tôn thêm vẻ đẹp cho mọi không gian nội thất. Kích thước lớn lên tới 75 inch thích hợp với những buổi tụ họp giải trí cùng gia đình, bạn bè trong những căn phòng rộng rãi như phòng khách, phòng họp hay các nhà hàng, quán café.','https://hc.com.vn/i/ecommerce/media/ckeditor_2872175.jpg','',''),
		(7,N'Hình ảnh sắc nét, chất lượng hoàn hảo với độ phân giải 8K',N'Khám phá những khung hình với chất lượng hình ảnh siêu nét trên Smart Tivi LG 8K 75NANO95TNA nhờ số điểm ảnh lên đến 33 triệu nhiều hơn gấp 4 lần so với độ phân giải 4K.','https://hc.com.vn/i/ecommerce/media/ckeditor_2872176.jpg','',''),
		(7,N'Màu sắc thuần khiết và chính xác nhờ công nghệ NanoCell',N'Tivi LG NanoCell sử dụng các hạt nano siêu nhỏ để hoạt động như các bộ lọc màu hấp thụ ánh sáng dư thừa đồng thời giúp giảm hiện tượng sai lệch màu sắc khi hiển thị trên màn hình, đảm bảo độ sáng cao và tăng cường độ tinh khiết màu sắc, cho trải nghiệm từng khung hình rực rỡ, chân thật và sống động hơn. Đồng thời, TV LG NanoCell 8K 75 inch 75NANO95TNA  còn được công nghệ Billion Rich Colors hỗ trợ mang lại phổ màu rộng và đa dạng.','https://hc.com.vn/i/ecommerce/media/ckeditor_2872172.jpg',N'Hơn thế nữa, TV LG NanoCell đã nhận được chứng nhận “Không có nguy cơ LED quang sinh học” từ Underwriters Laboratories (UL), đảm bảo đôi mắt của bạn được bảo vệ tránh ánh sáng có hại phát ra.',''),
		(7,N'Bộ xử lý AI 8K α9 thế hệ thứ 3 tự động phân tích, nâng cấp chất lượng hình ảnh và âm thanh',N'Với ứng dụng các thuật toán chuyên sâu, bộ xử lý α9 AI 8K thế hệ thứ 3 tận dụng công nghệ trí tuệ nhân tạo thông minh tự động phân tích, xử lý và nâng cấp nội dung lên chuẩn 8K mang đến trải nghiệm xem ấn tượng hơn.','https://hc.com.vn/i/ecommerce/media/ckeditor_2872155.jpg',N'Tính năng AI 8K Upscaling đem đến khả năng phân tích nội dung, thuật toán giảm nhiễu 6 bước và tăng cường độ sắc nét dựa trên tần số đáp ứng tín hiệu từ nội dung độ phân giải thấp hơn.',''),
		(7,N'Tăng cường độ tương phản với công nghệ Full Array Dimming',N'Với khả năng tắt mở độc lập những bóng đèn LED Full Array Dimming giúp tivi hiển thị màu đen gần như tuyệt đối làm nổi bật rõ sự tương phản giữa vùng sáng và vùng tối một cách chính xác.','https://hc.com.vn/i/ecommerce/media/ckeditor_2872156.jpg',N'Hơn thế nữa, công nghệ Ultra Luminance PRO được kết hợp để sử dụng năng lượng không cần thiết từ các vùng tối để tăng cường cho năng lượng các vùng sáng giúp cân bằng độ sáng cho hình ảnh rực rỡ mà không hề bị chói.',''),
		(7,N'Rạp chiếu phim thu nhỏ với công nghệ 8K Cinema HDR',N'Sự kết hợp giữa âm thanh đỉnh cao kết hợp với chất lượng hình ảnh 8K HDR tăng cường dải tương phản động mở rộng nhờ 4 chuẩn định dạng: HDR10 Pro, HLG Pro, Dolby Vision và HDR Effect mang đến trải nghiệm xem phim hấp dẫn tuyệt đỉnh.','https://hc.com.vn/i/ecommerce/media/ckeditor_2872154.jpg','',''),
		(7,N'Tận hưởng hình ảnh, màu sắc chuẩn xác ở mọi góc nhìn',N'Công nghệ Wide Viewing Angle mang đến màu sắc chuẩn xác từ bất cứ góc nhìn nào mà không bị biến dạng trên màn hình rộng. Smart Tivi LG NanoCell 8K 75 inch 75NANO95TNA với Nano Accuracy còn duy trì màu sắc sống động trên tất cả các vị trí của màn hình nhờ đó, bạn có thể thưởng thức tivi với màu sắc chân thật và rực rỡ từ mọi chỗ ngồi, kể cả ở khu vực có nhiều ánh sáng vẫn không bị chói.','https://hc.com.vn/i/ecommerce/media/ckeditor_2872151.jpg','',''),
		(7,N'Cảm nhận đúng ý đồ đạo diễn muốn truyền tải qua các bộ phim với công nghệ Filmmaker Mode',N'Bộ xử lý sẽ tự động điều chỉnh hình ảnh, tắt làm mịn chuyển động để có hiệu ứng hình ảnh chuyển động đầy đủ. Bạn sẽ được thưởng thức những bộ phim một cách trọn ven để cảm nhận chính xác ý định sáng tạo và kinh nghiệm điện ảnh mà đạo diễn muốn truyền tải đến cho người xem.','https://hc.com.vn/i/ecommerce/media/ckeditor_2872173.jpg','',''),
		(7,N'Đắm chìm trong những trận game cực đỉnh',N'LG 75NANO95TNA cho phép người dùng điều khiển hoàn toàn và ngay lập tức các trò chơi mà không có bất kỳ độ trễ nào giúp nắm bắt toàn bộ diễn biến một cách chính xác, cơ hội giành chiến thắng dễ dàng hơn bao giờ hết. Cấu hình HGiG ghi nhận hiệu suất TV và chất lượng hình ảnh sau đó điều chỉnh đồ họa HDR để mang đến trải nghiệm chơi game HDR tuyệt đỉnh.','https://hc.com.vn/i/ecommerce/media/ckeditor_2872150.jpg','',''),



insert into ThongSo(SanPhamID,ThuocTinh,GiaTri)
	values(1,N'Bảo hành',N'2 Năm'),
		(1,N'Loại Tivi', N'Smart Tivi'),
		(1,N'Kích thước tivi',N'55"'),
		(1,N'Khoảng kích thước màn hình',N'Từ 55 - 64 inch'),
		(1,N'Công nghệ màn hình',N'Nanocell'),
		(1,N'Độ phân giải',N'Ultra HD 8K (7680 x 4320 Pixel)'),
		(1,N'Năm Ra mắt',N'2020'),
		(2,N'Xuất xứ',N'Indonesia'),
		(2,N'Bảo hành',N'2 Năm'),
		(2,N'Loại Tivi',N'Smart tivi'),
		(2,N'Kích thước màn hình',N'75"'),
		(2,N'Khoảng kích thước màn hình',N'75 inch trở lên'),
		(2,N'Công nghệ màn hình',N'Nanocell'),
		(2,N'Độ phân giải',N'Ultra HD 8k'),
		(2,N'Bluetooth',N'Có(kết nối loa bluetooth)'),
		(3,N'Xuất xứ',N'Việt nam'),
		(3,N'Bảo hành',N'2 Năm'),
		(3,N'Loại Tivi',N'Smart tivi'),
		(3,N'Kích thước màn hình',N'75"'),
		(3,N'Khoảng kích thước màn hình',N'75 inch trở lên'),
		(3,N'Công nghệ màn hình',N'QLED'),
		(3,N'Độ phân giải',N'Ultra HB 8k'),
		(3,N'Bluetooth',N'Có'),
		(4,N'Xuất xứ',N'Việt nam'),
		(4,N'Bảo hành',N'2 Năm'),
		(4,N'Loại Tivi',N'Smart tivi'),
		(4,N'Kích thước màn hình',N'75"'),
		(4,N'Khoảng kích thước màn hình',N'75 inch trở lên'),
		(4,N'Công nghệ màn hình',N'QLED'),
		(4,N'Độ phân giải',N'Ultra HB 8k'),
		(4,N'Bluetooth',N'Có'),
		(4,N'Cổng lan',N'Có'),
		(4,N'Cổng HDMI',N'4 Cổng'),
		(5,N'Xuất xứ',N'Việt nam'),
		(5,N'Bảo hành',N'2 Năm'),
		(5,N'Loại Tivi',N'Smart tivi'),
		(5,N'Kích thước màn hình',N'82"'),
		(5,N'Khoảng kích thước màn hình',N'75 inch trở lên'),
		(5,N'Công nghệ màn hình',N'QLED'),
		(5,N'Độ phân giải',N'Ultra HB 8k'),
		(5,N'Bluetooth',N'Có'),
		(5,N'Cổng lan',N'Có'),
		(5,N'Cổng HDMI',N'4 Cổng'),
		(5,N'Cổng xuất âm thanh',N'Cổng Optical(Digital Audio Out)'),
		(5,N'Các ứng dụng sẵn có',N'Youtube, Netflix, Trình duyệt web, Kho ứng dụng'),
		(6,N'Xuất xứ',N'Việt nam'),
		(6,N'Bảo hành',N'2 Năm'),
		(6,N'Loại Tivi',N'Smart tivi'),
		(6,N'Kích thước màn hình',N'82"'),
		(6,N'Khoảng kích thước màn hình',N'75 inch trở lên'),
		(6,N'Công nghệ màn hình',N'QLED'),
		(6,N'Độ phân giải',N'Ultra HD 8k'),
		(6,N'Bluetooth',N'Có'),
		(6,N'Cổng lan',N'Có'),
		(6,N'Cổng HDMI',N'4 Cổng'),
		(6,N'Cổng xuất âm thanh',N'Cổng Optical(Digital Audio Out)'),
		(6,N'Các ứng dụng sẵn có',N'Youtube, Netflix, Trình duyệt web, Kho ứng dụng'),
		(6,N'Tích hợp đầu thu kỹ thuật số',N'Chuẩn DVB-T2'),
		(7,N'Xuất xứ',N'Indonesia'),
		(7,N'Bảo hành',N'2 Năm'),
		(7,N'Loại Tivi',N'Smart tivi'),
		(7,N'Kích thước màn hình',N'82"'),
		(7,N'Khoảng kích thước màn hình',N'75 inch trở lên'),
		(7,N'Công nghệ màn hình',N'Nanocell'),
		(7,N'Độ phân giải',N'Ultra HD 8k'),
		(7,N'Bluetooth',N'Có(kết nối loa bluetooth)'),
		(7,N'Cổng lan',N'Có'),
		(7,N'Cổng HDMI',N'4 Cổng'),
		(7,N'Cổng xuất âm thanh',N'HDMI ARC (hỗ trợ eARC), Cổng SPDIF (Digital Audio Out)'),
		(7,N'Các ứng dụng sẵn có',N'YouTube, Netflix, Trình duyệt web, LG Content Store'),
		(7,N'Tích hợp đầu thu kỹ thuật số',N'Chuẩn DVB-T2'),

